---

- name: shell
  hosts: "{{ hosts }}"
  become: yes

  vars:
    source_folder: ./source_files
    source_files: ./source_files/playbook2.yml
    destin_file: /tmp
    message: This is
    j2_files: ./source_files/index.j2
    nginx_ubuntu_path: /var/www/html
  pre_tasks:
  - debug: msg="Start pre tasks"

  roles:
  - role: provision
  - role: devops
    vars:
      destin_file: /home/vagrant

  tasks:
  - name: ls
    shell: ls -la /tmp
    register: result
    tags:
    - test

  - debug:
      var: result

  - name: Create folder for backup
    include: ./custom/create_backup.yml

  - name: Ansible date fact example
    debug:
      var=ansible_date_time.date
    tags:
    - test

  - set_fact: OS="{{ message }} {{ ansible_nodename }}"
  - name: Get OS
    debug:
      var: OS
      var: ansible_facts.ansible_all_ipv4_addresses
    tags:
    - test


# create env for ubuntu
  - name: Create environment varibles
    shell: |
      tee -a /home/vagrant/env.txt << EOF
      export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      export AWS_DEFAULT_REGION=us-west-2
#  - name: Source env
#    shell: |
#      source /home/vagrant/env.txt

  - name: Source env.txt delete
    shell: rm  -rf /home/vagrant/env.txt
    ignore_errors: yes

  - name: Restart servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait untill UP
    wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 45
    delegate_to: 127.0.0.1
    ignore_errors: yes
    register: status

  - debug: var=status

  - debug: msg={{status is failed}}

  - name: The servers is UP
    shell: echo The servers is UP

  post_tasks:
  - debug: msg="SUCCESS"
