---
# tasks file for devops

- name: Update for centos
  shell: yum update -y
  when: ansible_os_family == "RedHat"

- name: Install packages for CENTOS
  yum: name={{ item }} state=installed
  when: ansible_os_family == "RedHat"
  loop:
    - tree
    - nano
    - git
    - docker
    - ansible
    - epel-release
    - python34-pip
    - python34-setuptools

- name: Start docker
  service: name=docker state=started enabled=yes
  notify: Restart_docker

- name: Update for UBUNTU
  shell: apt update -y
  when: ansible_os_family != "RedHat"

- name: Install packages for UBUNTU
  apt: name={{ item }} state=installed
  when: ansible_os_family != "RedHat"
  with_items:
    - tree
    - nano
    - git
    - docker.io
    - ansible
    - nginx
    - python3-pip

- name: Start docker
  service: name=docker state=started enabled=yes
  when: ansible_nodename == "centos"

- block: # For centos
    - name: Ansible date fact example
      debug:
        var=ansible_date_time.date
  when: ansible_nodename == "centos"



- name: Copy j2 into ubuntu
  template: src=index.j2 dest={{ nginx_ubuntu_path }}/index.html mode=0555
  when: ansible_os_family != "RedHat"
